BASE_DIR    = $(PWD)/..
PROJECT_DIR = $(BASE_DIR)/dv/uvm/$(PROJECT_NAME)

regr_gui:
	$(MAKE) -f $(PROJECT_DIR)/scripts/Makefile regr_gui

regr_batch:
	$(MAKE) -f $(PROJECT_DIR)/scripts/Makefile regr_batch

clean_all:
	@rm -rf $(BASE_DIR)/work/*
